export const HOTLIST_ACTION = 'HOTLIST_ACTION';
export const HOTLIST_REQUEST = 'HOTLIST_REQUEST';
export const HOTLIST_SUCCESS = 'HOTLIST_SUCCESS';
export const HOTLIST_FAILURE = 'HOTLIST_FAILURE';

export const HOTDETAIL_ACTION = 'HOTDETAIL_ACTION';
export const HOTDETAIL_REQUEST = 'HOTDETAIL_REQUEST';
export const HOTDETAIL_SUCCESS = 'HOTDETAIL_SUCCESS';
export const HOTDETAIL_FAILURE = 'HOTDETAIL_FAILURE';