// export const HOTLIST_ACTION = 'HOTLIST_ACTION';
// export const HOTLIST_REQUEST = 'HOTLIST_REQUEST';
// export const HOTLIST_SUCCESS = 'HOTLIST_SUCCESS';
// export const HOTLIST_FAILURE = 'HOTLIST_FAILURE';

// export const HOTDETAIL_ACTION = 'HOTDETAIL_ACTION';
// export const HOTDETAIL_REQUEST = 'HOTDETAIL_REQUEST';
// export const HOTDETAIL_SUCCESS = 'HOTDETAIL_SUCCESS';
// export const HOTDETAIL_FAILURE = 'HOTDETAIL_FAILURE';


//NEWSTOCK
export const NEWSTOCK_DETAIL_ACTION = 'NEWSTOCK_DETAIL_ACTION';
export const NEWSTOCK_DETAIL_REQUEST = 'NEWSTOCK_DETAIL_REQUEST';
export const NEWSTOCK_DETAIL_SUCCESS = 'NEWSTOCK_DETAIL_SUCCESS';
export const NEWSTOCK_DETAIL_FAILURE = 'NEWSTOCK_DETAIL_FAILURE';

export const NEWSTOCK_LIST_ACTION = 'NEWSTOCK_LIST_ACTION';
export const NEWSTOCK_LIST_REQUEST = 'NEWSTOCK_LIST_REQUEST';
export const NEWSTOCK_LIST_SUCCESS = 'NEWSTOCK_LIST_SUCCESS';
export const NEWSTOCK_LIST_FAILURE = 'NEWSTOCK_LIST_FAILURE';

export const NEWSTOCK_OBSERVER_ACTION = 'NEWSTOCK_OBSERVER_ACTION';
export const NEWSTOCK_OBSERVER_REQUEST = 'NEWSTOCK_OBSERVER_REQUEST';
export const NEWSTOCK_OBSERVER_SUCCESS = 'NEWSTOCK_OBSERVER_SUCCESS';
export const NEWSTOCK_OBSERVER_FAILURE = 'NEWSTOCK_OBSERVER_FAILURE';

export const NEWSTOCK_OBSERVER_ORDER_ACTION = 'NEWSTOCK_OBSERVER_ORDER_ACTION';
export const NEWSTOCK_OBSERVER_ORDER_REQUEST = 'NEWSTOCK_OBSERVER_ORDER_REQUEST';
export const NEWSTOCK_OBSERVER_ORDER_SUCCESS = 'NEWSTOCK_OBSERVER_ORDER_SUCCESS';
export const NEWSTOCK_OBSERVER_ORDER_FAILURE = 'NEWSTOCK_OBSERVER_ORDER_FAILURE';

export const NEWSTOCK_OBSERVER_UNORDER_ACTION = 'NEWSTOCK_OBSERVER_UNORDER_ACTION';
export const NEWSTOCK_OBSERVER_UNORDER_REQUEST = 'NEWSTOCK_OBSERVER_UNORDER_REQUEST';
export const NEWSTOCK_OBSERVER_UNORDER_SUCCESS = 'NEWSTOCK_OBSERVER_UNORDER_SUCCESS';
export const NEWSTOCK_OBSERVER_UNORDER_FAILURE = 'NEWSTOCK_OBSERVER_UNORDER_FAILURE';